all: 1.o func1.o ols.o olsv.o olsn.o olsi.o olsb.o omvv.o grep.o grepc.o grepn.o grepv.o grepi.o aps.o apsd_done.o apse_done.o apsr_done.o apsa_done.o all_ls.o all_cp_mv.o all_grep.o all_ps.o	
	gcc 1.o func1.o ols.o olsv.o olsn.o olsi.o olsb.o omvv.o grep.o grepc.o grepn.o grepv.o grepi.o aps.o apsd_done.o apse_done.o apsr_done.o apsa_done.o all_ls.o all_cp_mv.o all_grep.o all_ps.o -lreadline -o myshell
1.o: 1.c
	gcc -c 1.c -o 1.o
func1.o: func1.c
	gcc -c func1.c -o func1.o
ols.o: ols.c
	gcc -c ols.c -o ols.o
olsv.o: olsv.c
	gcc -c olsv.c -o olsv.o	
olsn.o: olsn.c
	gcc -c olsn.c -o olsn.o	
olsi.o: olsi.c
	gcc -c olsi.c -o olsi.o		
olsb.o: olsb.c
	gcc -c olsb.c -o olsb.o	
omvv.o: omvv.c
	gcc -c omvv.c -o omvv.o			
grep.o: grep.c
	gcc -c grep.c -o grep.o		
grepc.o: grepc.c
	gcc -c grepc.c -o grepc.o			
grepn.o: grepn.c
	gcc -c grepn.c -o grepn.o		
grepv.o: grepv.c
	gcc -c grepv.c -o grepv.o	
grepi.o: grepi.c
	gcc -c grepi.c -o grepi.o						
aps.o: aps.c
	gcc -c aps.c -o aps.o
apsd_done.o: apsd_done.c
	gcc -c apsd_done.c -o apsd_done.o
apse_done.o: apse_done.c
	gcc -c apse_done.c -o apse_done.o
apsr_done.o: apsr_done.c
	gcc -c apsr_done.c -o apsr_done.o	
apsa_done.o: apsa_done.c
	gcc -c apsa_done.c -o apsa_done.o			
all_ls.o: all_ls.c
	gcc -c all_ls.c -o all_ls.o
all_cp_mv.o: all_cp_mv.c
	gcc -c all_cp_mv.c -o all_cp_mv.o
all_grep.o: all_grep.c
	gcc -c all_grep.c -o all_grep.o	
all_ps.o: all_ps.c
	gcc -c all_ps.c -o all_ps.o	
